name: Build

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - {
              name: "Ubuntu Latest",
              os: "ubuntu-latest",
              flags: "-GNinja"
          }
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc \
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-jammy.list http://packages.lunarg.com/vulkan/lunarg-vulkan-jammy.list \
          sudo apt-get update && \
          sudo apt-get install \
          cmake ninja-build \
          libx11-xcb-dev \
          libxcb-render-util0-dev \
          libxcb-xkb-dev \
          libxcb-icccm4-dev \
          libxcb-image0-dev \
          libxcb-keysyms1-dev \
          libxcb-randr0-dev \
          libxcb-shape0-dev \
          libxcb-sync-dev \
          libxcb-xfixes0-dev \
          libxcb-xinerama0-dev \
          libxcb-dri3-dev \
          libxcb-cursor-dev \
          libgl1-mesa-dev \
          libxcb-util-dev \
          libxcb-util0-dev \
          libglu1-mesa-dev \
          libglu1-mesa \
          xorg-dev \
          vulkan-sdk

      - name: Install Conan
        uses: turtlebrowser/get-conan@main
        with:
          version: 1.60.1

      - name: Configure CMake
        shell: bash
        run: cmake -B build -DCMAKE_BUILD_TYPE="Release" ${{matrix.platform.flags}}

      - name: Build
        shell: bash
        run: cmake --build build
